name: Homey App Validation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - run: npm i -g homey
      - run: npm i
      - run: npm run build
      - name: Enable write permission for .homeybuild
        run: |
          mkdir -p .homeybuild
          chmod -R 777 .homeybuild
      - name: Validate Homey App
        run: homey app validate -l publish
